name: Attendly Production API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, main]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm
        run: npm install -g npm

      - name: Install dependencies
        run: npm install

      - name: Run migration
        run: npm run prisma:migrate:prod

      - name: Run migration
        run: npm run prisma:generate:prod

      - name: Build project
        run: npm run build
